package com.iii.premia.customervatrate.services.customervatrate;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "CustomerVATRateService", targetNamespace = "http://CustomerVATRate.services.CustomerVATRate.premia.iii.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface CustomerVATRateService {

	/**
	 * 
	 * @param customerVATRateRequestInfo
	 * @return returns com.iii.premia.customervatrate.services.customervatrate.
	 *         CustomerVATRateResponseInfo
	 * @throws CustomerVATRateScheduleException
	 */
	@WebMethod(operationName = "CustomerVATRate")
	@WebResult(name = "CustomerVATRateInformation", partName = "CustomerVATRateInformation")
	public CustomerVATRateResponseInfo customerVATRate(
			@WebParam(name = "CustomerVATRateRequestInfo", partName = "CustomerVATRateRequestInfo") CustomerVATRateRequestInfo customerVATRateRequestInfo)
			throws CustomerVATRateScheduleException;

}
