package com.iii.premia.customervatrate.services.customervatrate;

import javax.xml.ws.WebFault;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebFault(name = "DraftScheduleFault", targetNamespace = "http://CustomerVATRate.services.CustomerVATRate.premia.iii.com/")
public class CustomerVATRateScheduleException extends Exception {

	/**
	 * Java type that goes as soapenv:Fault detail element.
	 * 
	 */
	private ReferralExceptionBean faultInfo;

	/**
	 * 
	 * @param message
	 * @param faultInfo
	 */
	public CustomerVATRateScheduleException(String message,
			ReferralExceptionBean faultInfo) {
		super(message);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @param message
	 * @param faultInfo
	 * @param cause
	 */
	public CustomerVATRateScheduleException(String message,
			ReferralExceptionBean faultInfo, Throwable cause) {
		super(message, cause);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @return returns fault bean:
	 *         com.iii.premia.customervatrate.services.customervatrate
	 *         .ReferralExceptionBean
	 */
	public ReferralExceptionBean getFaultInfo() {
		return faultInfo;
	}

}
