package com.iii.premia.customervatrate.services.customervatrate;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * CustomerVATRate service = new CustomerVATRate();
 * CustomerVATRateService portType = service.getCustomerVATRateServicePort();
 * portType.customerVATRate(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "CustomerVATRate", targetNamespace = "http://CustomerVATRate.services.CustomerVATRate.premia.iii.com/", wsdlLocation = "http://94.56.152.169:8080/CustomerVATRateTest/CustomerVATRate?wsdl")
public class CustomerVATRate extends Service {

	private final static URL CUSTOMERVATRATE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.iii.premia.customervatrate.services.customervatrate.CustomerVATRate.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.iii.premia.customervatrate.services.customervatrate.CustomerVATRate.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://94.56.152.169:8080/CustomerVATRateTest/CustomerVATRate?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://94.56.152.169:8080/CustomerVATRateTest/CustomerVATRate?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		CUSTOMERVATRATE_WSDL_LOCATION = url;
	}

	public CustomerVATRate(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public CustomerVATRate() {
		super(
				CUSTOMERVATRATE_WSDL_LOCATION,
				new QName(
						"http://CustomerVATRate.services.CustomerVATRate.premia.iii.com/",
						"CustomerVATRate"));
	}

	/**
	 * 
	 * @return returns CustomerVATRateService
	 */
	@WebEndpoint(name = "CustomerVATRateServicePort")
	public CustomerVATRateService getCustomerVATRateServicePort() {
		return super
				.getPort(
						new QName(
								"http://CustomerVATRate.services.CustomerVATRate.premia.iii.com/",
								"CustomerVATRateServicePort"),
						CustomerVATRateService.class);
	}

}
